package com.academy.management.model;

import java.util.Date;

public class FeeApp {

    private Long id; // Auto-generated by DB
    private Long businessNumber; // Auto-increment starting from 1
    private Long studentId;
    private Long courseId;
    private Double amountPaid = 0.0; // Default value
    private Date paymentDate = new Date(); // Default to current date
    private String status = "PAID"; // Default value
    private Date createdAt = new Date(); // Default to current date
    private Date updatedAt;

    // Getters and Setters

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getBusinessNumber() {
        return businessNumber;
    }

    public void setBusinessNumber(Long businessNumber) {
        this.businessNumber = businessNumber;
    }

    public Long getStudentId() {
        return studentId;
    }

    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

    public Long getCourseId() {
        return courseId;
    }

    public void setCourseId(Long courseId) {
        this.courseId = courseId;
    }

    public Double getAmountPaid() {
        return amountPaid;
    }

    public void setAmountPaid(Double amountPaid) {
        this.amountPaid = amountPaid;
    }

    public Date getPaymentDate() {
        return paymentDate;
    }

    public void setPaymentDate(Date paymentDate) {
        this.paymentDate = paymentDate;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}
